displayName=Ent Pathfinder
author=JustinCO2
support=
description=Draws a Shortest Path to called Forestry ent events on the forestry world.
tags=forestry,ent,entling,woodcutting,shortestpath,scouting
plugins=com.entpathfinder.EntPathfinderPlugin
